use proofir_core::{canonical_bytes, validate_envelope};
use serde_json::Value;

// Golden vector generated by ladon.proofir_v3; changing either implementation
// requires an explicit ProofIR contract-version decision.
#[test]
fn canonical_bytes_and_identity_match_python_vector() {
    let vector: Value = serde_json::from_str(include_str!(
        "../../../tests/fixtures/proofir_v3_parity/normalized-row-vector.json"
    ))
    .unwrap();
    let artifact = vector["artifact"].clone();
    let expected = vector["canonicalJson"].as_str().unwrap();
    assert_eq!(canonical_bytes(&artifact).unwrap(), expected.as_bytes());
    assert_eq!(
        validate_envelope(artifact).unwrap().content_id,
        vector["artifactId"].as_str().unwrap()
    );
}
