from pathlib import Path
import hashlib,json,shutil,sqlite3
root=Path.cwd();state=root/'.codex/state/application-handoff-r60';run=Path((state/'run-path').read_text().strip());out=root/'openspec/changes/ladon-goal-capture-and-application-probes/evidence/application-handoff-r60';out.mkdir(exist_ok=True)
for base,destination in [(state,'reproduce'),(run,'field')]:
 for p in base.rglob('*'):
  if not p.is_file() or p.is_symlink() or 'selected-source.sqlite' in p.name or '.lake' in p.parts:continue
  dest=out/destination/p.relative_to(base);dest.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(p,dest)
identity=json.loads((run/'fixture-identity.json').read_text());sources={}
for name in ('a','b'):
 cap=json.loads((run/('capture-'+name+'.stdout')).read_text());source=run/'fixture'/cap['capture']['source']['path'];assert cap['capture']['source']['digest']=='sha256:'+hashlib.sha256(source.read_bytes()).hexdigest();sources[source.name]=cap['capture']['source']['digest'];assert len(cap['capture']['environment']['compiledInventory']['modules'])==10523
selection=json.loads((run/'search-source-selection.json').read_text());assert hashlib.sha256(Path(selection['source']).read_bytes()).hexdigest()==selection['sha256']
checks=json.loads((run/'required-qualification-commands.json').read_text());assert all(r['returncode']==0 and not any(r[k] for k in ('timed_out','memory_limited','output_limited')) for r in checks)
commands=[json.loads(p.read_text()) for p in sorted(run.glob('*.command.json'))]
v={'schema':'ladon-captured-goal-handoff-acceptance-v1','candidate':identity['qualifiedCandidate'],'scope':'root-operated fixed-epoch capture, exact selected-source module lexical discovery and original-goal completion; not blind LLM comparison, unrestricted discovery, source/compiled correspondence or exposition review','qualifiedCompletionRecord':'../application-completion-r59/acceptance.json','sources':sources,'searchSelection':selection,'goalA':json.loads((run/'completion-a-summary.json').read_text()),'goalB':json.loads((run/'completion-b-summary.json').read_text()),'resourceControls':json.loads((run/'resource-controls-summary.json').read_text()),'requiredQualification':checks,'handoffBudget':json.loads((state/'budget.json').read_text()),'priorCompletionBudgetFrozen':json.loads((root/'.codex/state/application-completion-r59/root-trials/budget.json').read_text()),'commandCount':len(commands),'largestCommandPeakRssBytes':max(r['peak_rss_bytes'] or 0 for r in commands),'actualSourcesUnchanged':True,'rootHead':__import__('subprocess').check_output(['git','rev-parse','HEAD'],text=True).strip(),'rootIndexSha256':hashlib.sha256((root/'.git/index').read_bytes()).hexdigest()}
assert v['goalA']['status']=='completed' and v['goalB']['status']=='incomplete';assert v['rootHead']==v['candidate']['sourceHead'] and v['rootIndexSha256']==v['candidate']['sourceIndexSha256'];(out/'acceptance.json').write_text(json.dumps(v,indent=2)+'\n')
con=sqlite3.connect(root/'.codex/state/ultra-result-evidence.sqlite3');con.row_factory=sqlite3.Row;(out/'portfolio.json').write_text(json.dumps([dict(r) for r in con.execute('SELECT * FROM posts WHERE post_id BETWEEN 822 AND 825 ORDER BY post_id')],indent=2)+'\n');print(json.dumps({'entries':sum(p.is_file() for p in out.rglob('*')),'peakRssBytes':v['largestCommandPeakRssBytes'],'customSeconds':v['handoffBudget']['chargedUpperBoundSeconds']}))
