#!/usr/bin/env python3
"""Generate Ladon's supported-feature matrix from executable pytest gates."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

FEATURES: tuple[dict[str, Any], ...] = (
    {
        "id": "architecture-review",
        "tier": "core",
        "summary": "Installed analysis, architecture policy, and bounded report output.",
        "tests": (
            "tests/test_installed_cli_contract.py::test_installed_analyzer_process_contract",
            "tests/test_architecture_policy.py::test_architecture_policy_flags_direct_peer_imports_from_globs",
        ),
    },
    {
        "id": "semantic-declaration-search",
        "tier": "core",
        "summary": "Lexical/type shortlists plus explicit Lean candidate-application checks.",
        "tests": (
            "tests/test_proof_search_type.py::test_type_search_returns_lexical_shortlist_and_diagnostics",
            "tests/test_semantic_candidate_lean_integration.py::test_installed_cli_emits_batch_closed_semantic_evidence",
            "tests/test_semantic_build_mode.py::test_installed_cli_rejects_removed_semantic_mode_without_invoking_lean",
        ),
    },
    {
        "id": "evidence-and-lineage-inspection",
        "tier": "core",
        "summary": "Stored ProofIR dossiers and exact compiled theorem-lineage persistence.",
        "tests": (
            "tests/test_proofir_v3_installed_workflow_contract.py::test_installed_dossier_reports_coverage_and_limitations",
            "tests/test_theorem_lineage_store.py::test_ingestion_is_constrained_and_status_is_fresh",
        ),
    },
    {
        "id": "report-atlas",
        "tier": "optional",
        "summary": "Multi-report atlas and SQLite review projections.",
        "tests": (
            "tests/test_atlas_sqlite.py::test_write_atlas_sqlite_creates_query_tables",
        ),
    },
    {
        "id": "theorem-capsules",
        "tier": "optional",
        "summary": "Pinned module-prefix materialization and replay packaging.",
        "tests": (
            "tests/test_installed_theorem_cli_contract.py::test_installed_theorem_capsule_help_is_caller_neutral",
        ),
    },
    {
        "id": "runsets-and-reportsets",
        "tier": "optional",
        "summary": "Versioned batch execution and independent report publication.",
        "tests": (
            "tests/test_runset_cli.py::test_runset_cli_publishes_clean_independent_reports",
        ),
    },
)


def project_root() -> Path:
    return Path(__file__).resolve().parents[1]


def matrix_payload() -> dict[str, Any]:
    return {
        "schemaVersion": 1,
        "artifactKind": "ladon_supported_feature_matrix",
        "source": "repository-owned executable pytest nodes",
        "features": [
            {
                **{key: value for key, value in feature.items() if key != "tests"},
                "tests": list(feature["tests"]),
                "verificationCommand": "uv run --locked pytest -q "
                + " ".join(feature["tests"]),
            }
            for feature in FEATURES
        ],
    }


def render_json() -> str:
    return json.dumps(matrix_payload(), indent=2, sort_keys=True) + "\n"


def render_markdown() -> str:
    lines = [
        "# Supported feature matrix",
        "",
        "This file is generated by `scripts/generate_supported_feature_matrix.py`.",
        "A feature is listed only with repository-owned executable pytest nodes.",
        "",
        "| Workflow | Tier | Contract | Executable gates |",
        "| --- | --- | --- | --- |",
    ]
    for feature in FEATURES:
        tests = "<br>".join(f"`{node}`" for node in feature["tests"])
        lines.append(
            f"| `{feature['id']}` | {feature['tier']} | {feature['summary']} | {tests} |"
        )
    lines.extend(
        [
            "",
            "The matrix records maintained support ownership, not a theorem-proof claim.",
            "Use `--verify-tests` to execute every listed gate before regeneration.",
            "",
        ]
    )
    return "\n".join(lines)


def verify_tests(root: Path) -> None:
    nodes = [node for feature in FEATURES for node in feature["tests"]]
    completed = subprocess.run(
        [sys.executable, "-m", "pytest", "-q", *nodes],
        cwd=root,
        check=False,
    )
    if completed.returncode:
        raise SystemExit(completed.returncode)


def write_or_check(path: Path, expected: str, *, check: bool) -> None:
    if check:
        actual = path.read_text(encoding="utf-8") if path.is_file() else ""
        if actual != expected:
            raise SystemExit(f"generated feature matrix is stale: {path}")
        return
    path.write_text(expected, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--verify-tests", action="store_true")
    args = parser.parse_args(argv)
    root = project_root()
    if args.verify_tests:
        verify_tests(root)
    write_or_check(root / "docs/SUPPORTED_FEATURE_MATRIX.json", render_json(), check=args.check)
    write_or_check(root / "docs/SUPPORTED_FEATURE_MATRIX.md", render_markdown(), check=args.check)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
