[package]
name = "proofir-ladon"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
proofir-core = { path = "../proofir-core" }
proofir-json = { path = "../proofir-json" }
proofir-validate = { path = "../proofir-validate" }
proofir-sqlite = { path = "../proofir-sqlite" }
serde_json.workspace = true
