"""Compatibility facade for deterministic Ladon atlas operations.

Atlas report adaptation, graph construction, reviewer-card derivation, and
Markdown rendering live in cohesive modules. Existing callers can continue to
import the supported surface from :mod:`ladon.atlas`.
"""

from __future__ import annotations

from ladon.atlas_cards import (
    atlas_reviewer_cards,
    bridge_report_summary,
    bridge_root,
    bridge_summaries_by_root,
    counts_by_key,
    empty_bridge_summary,
    finding_evidence_summaries,
    finding_labels,
    linked_nodes,
    low_confidence_join_count,
    merge_bridge_summary,
    region_labels,
    report_root,
    reviewer_card,
    strongest_evidence,
)
from ladon.atlas_graph import (
    Edge,
    Node,
    add_declaration_highlights,
    add_findings,
    add_metric_module,
    add_module_highlights,
    add_node,
    add_region_signal,
    add_report_payload,
    add_review_regions,
    add_root_module,
    atlas_summary,
    build_report_atlas,
    confidence_counts,
    declaration_evidence_summary,
    declaration_node_id,
    declaration_rows_by_name,
    edge,
    edge_sort_key,
    module_node_id,
    packet_evidence_summary,
    packet_incomplete,
    packet_stale,
    plural_key,
    projected_collection_count,
    repo_key_from_path,
    report_node_id,
    top_key,
    valid_packet_rows,
)
from ladon.atlas_markdown import (
    bridge_trust_notes,
    format_bridge_diagnostics,
    format_declaration_evidence,
    format_packet_evidence,
    render_atlas_markdown,
    render_reviewer_cards_markdown,
    report_table_lines,
    reviewer_card_lines,
    summary_lines,
)
from ladon.atlas_report_reader import (
    atlas_report_view,
    inflate_declaration_evidence,
    is_ladon_report_payload,
)

__all__ = [
    "Edge",
    "Node",
    "add_declaration_highlights",
    "add_findings",
    "add_metric_module",
    "add_module_highlights",
    "add_node",
    "add_region_signal",
    "add_report_payload",
    "add_review_regions",
    "add_root_module",
    "atlas_report_view",
    "atlas_reviewer_cards",
    "atlas_summary",
    "bridge_report_summary",
    "bridge_root",
    "bridge_summaries_by_root",
    "bridge_trust_notes",
    "build_report_atlas",
    "confidence_counts",
    "counts_by_key",
    "declaration_evidence_summary",
    "declaration_node_id",
    "declaration_rows_by_name",
    "edge",
    "edge_sort_key",
    "empty_bridge_summary",
    "finding_evidence_summaries",
    "finding_labels",
    "format_bridge_diagnostics",
    "format_declaration_evidence",
    "format_packet_evidence",
    "inflate_declaration_evidence",
    "is_ladon_report_payload",
    "linked_nodes",
    "low_confidence_join_count",
    "merge_bridge_summary",
    "module_node_id",
    "packet_evidence_summary",
    "packet_incomplete",
    "packet_stale",
    "plural_key",
    "projected_collection_count",
    "region_labels",
    "render_atlas_markdown",
    "render_reviewer_cards_markdown",
    "repo_key_from_path",
    "report_node_id",
    "report_root",
    "report_table_lines",
    "reviewer_card",
    "reviewer_card_lines",
    "strongest_evidence",
    "summary_lines",
    "top_key",
    "valid_packet_rows",
]
