"""Text-based Lean module discovery for Ladon's clean-core smoke path.

This module deliberately does not invoke Lake. It gives Ladon a fast, tested
module-DAG input surface while Lean-native declaration extraction is rebuilt in
later packets.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Sequence

from ladon.ir import LeanImport, LeanLexicalMarker, LeanModule, LeanTextDeclaration
from ladon.lean_layout import (
    LeanSourceMap,
    discover_lean_source_map,
    module_name_under_root,
    root_for_path,
)


IMPORT_MODULE_RE = re.compile(r"^[A-Za-z0-9_.]+$")
GENERATED_COMMENT_RE = re.compile(r"\b(?:auto[- ]?generated|code generated|generated by)\b", re.IGNORECASE)
TRUST_CONSTRUCT_RE = re.compile(r"\b(?:sorry|admit|axiom)\b")
TODO_RE = re.compile(r"\b(?:TODO|FIXME)\b")
DECLARATION_KINDS = (
    "theorem",
    "lemma",
    "def",
    "abbrev",
    "instance",
    "structure",
    "class",
    "inductive",
    "opaque",
    "axiom",
    "constant",
)
DECLARATION_MODIFIERS = (
    "private",
    "protected",
    "noncomputable",
    "unsafe",
    "partial",
)
DECL_RE = re.compile(
    r"^[ \t]*(?:@\[[^\]]*\]\s*)*"
    rf"(?:(?:{'|'.join(DECLARATION_MODIFIERS)})\s+)*"
    rf"(?P<kind>{'|'.join(DECLARATION_KINDS)})\s+"
    r"(?P<name>[A-Za-z_][A-Za-z0-9_'.]*)",
    re.MULTILINE,
)


@dataclass(frozen=True)
class ModuleDiscovery:
    """Resolved module inventory for one Ladon clean-core run.

    `analysis_root_file` is the concrete Lean file selected by the CLI.
    `inventory_root` is the top-level namespace/file prefix scanned for the
    module DAG, for example `Quux` or `Mf`.
    """

    repo_root: Path
    analysis_root_file: Path
    analysis_root_module: str
    inventory_root: str
    modules: dict[str, LeanModule]
    discovery_status: str = "conventional_fallback"
    diagnostics: tuple[dict[str, Any], ...] = ()
    source_roots: tuple[str, ...] = ()


def module_name(repo_root: Path, file_path: Path) -> str:
    """Return the Lean module name implied by a repo-relative file path."""

    relative = file_path.relative_to(repo_root)
    return ".".join(relative.with_suffix("").parts)


def module_file(repo_root: Path, module: str) -> Path:
    """Return the conventional Lean file path for a module name."""

    return repo_root / Path(*module.split(".")).with_suffix(".lean")


def root_candidates(repo_root: Path, raw_root: str) -> list[Path]:
    """Return accepted file candidates for a CLI root value.

    The clean core accepts both repo-relative paths such as
    `Quux/Semantics/Propagation.lean` and module names such as
    `Quux.Semantics.Propagation`.
    """

    raw_path = Path(raw_root)
    candidates = absolute_or_relative_candidates(repo_root, raw_path)
    if raw_path.suffix != ".lean":
        candidates.append((repo_root / raw_path).with_suffix(".lean"))
        candidates.append(module_file(repo_root, raw_root))
        candidates.append(repo_root / Path(*raw_root.split(".")))
    return unique_paths(candidates)


def absolute_or_relative_candidates(repo_root: Path, raw_path: Path) -> list[Path]:
    """Interpret CLI paths as absolute paths or repo-relative paths."""

    if raw_path.is_absolute():
        return [raw_path]
    return [repo_root / raw_path]


def unique_paths(paths: Sequence[Path]) -> list[Path]:
    """Preserve candidate order while removing duplicate paths."""

    unique: list[Path] = []
    for path in paths:
        if path not in unique:
            unique.append(path)
    return unique


def infer_root_file(repo_root: Path) -> Path:
    """Infer the top-level root file or fail if the choice is ambiguous."""

    top_level = sorted(path for path in repo_root.glob("*.lean") if path.is_file())
    if len(top_level) == 1:
        return top_level[0].resolve()
    if top_level:
        raise ValueError("multiple top-level Lean roots exist; pass --root")
    raise ValueError("no top-level Lean root exists; pass --root")


def resolve_root_file(repo_root: Path, raw_root: str | None) -> Path:
    """Resolve the analysis root to a Lean file or directory inside `repo_root`."""

    if not raw_root:
        return infer_root_file(repo_root)
    existing = [
        path.resolve()
        for path in root_candidates(repo_root, raw_root)
        if path.is_file() or path.is_dir()
    ]
    if not existing:
        raise ValueError(f"could not resolve analysis root {raw_root!r}")
    return ensure_inside_repo(repo_root, existing[0])


def ensure_inside_repo(repo_root: Path, file_path: Path) -> Path:
    """Validate that a resolved root is a Lean file inside the target repo."""

    try:
        file_path.relative_to(repo_root)
    except ValueError as exc:
        raise ValueError(f"analysis root {file_path} is outside {repo_root}") from exc
    if file_path.is_dir():
        return file_path
    if file_path.suffix != ".lean":
        raise ValueError(f"analysis root {file_path} is not a Lean file")
    return file_path


def inventory_root_for(root_file: Path, repo_root: Path) -> str:
    """Choose the namespace prefix scanned for module-DAG inventory."""

    if root_file.is_dir():
        return module_name(repo_root, root_file)
    relative = root_file.relative_to(repo_root)
    if len(relative.parts) > 1:
        return relative.parts[0]
    return relative.with_suffix("").name.split(".")[0]


def inventory_files(repo_root: Path, inventory_root: str) -> list[Path]:
    """Return top-level and nested Lean files for one namespace prefix."""

    files: list[Path] = []
    namespace_path = Path(*inventory_root.split("."))
    top_file = (repo_root / namespace_path).with_suffix(".lean")
    top_dir = repo_root / namespace_path
    if top_file.is_file():
        files.append(top_file)
    if top_dir.is_dir():
        files.extend(sorted(top_dir.rglob("*.lean")))
    return unique_paths(files)


def parse_lean_module(
    repo_root: Path,
    file_path: Path,
    *,
    resolved_name: str | None = None,
    source_text: str | None = None,
) -> LeanModule:
    """Parse imports and declaration names with text-level regexes only."""

    text = (
        file_path.read_text(encoding="utf-8")
        if source_text is None
        else source_text
    )
    masked = mask_lean_comments_and_strings(text)
    relative = file_path.relative_to(repo_root)
    module = resolved_name or module_name(repo_root, file_path)
    import_sites = parse_import_sites(text, masked_text=masked)
    declarations = parse_text_declarations(text, masked_text=masked)
    return LeanModule(
        name=module,
        path=str(relative),
        imports=tuple(site.module for site in import_sites),
        import_sites=import_sites,
        line_count=len(text.splitlines()),
        tags=module_tags(module, relative, text),
        lexical_markers=parse_lexical_markers(text, masked_text=masked),
        declarations=tuple(row.name for row in declarations),
        declaration_evidence=declarations,
    )


def module_tags(module: str, relative_path: Path, text: str) -> tuple[str, ...]:
    """Return generic source tags inferred from common file conventions."""

    tags: list[str] = []
    if is_generated_module(module, relative_path, text):
        tags.append("generated")
    return tuple(tags)


def is_generated_module(module: str, relative_path: Path, text: str) -> bool:
    """Detect common generated-code markers without project-specific names."""

    return (
        generated_name_segments(module.split("."))
        or generated_name_segments(relative_path.with_suffix("").parts)
        or bool(GENERATED_COMMENT_RE.search("\n".join(text.splitlines()[:8])))
    )


def generated_name_segments(segments: Sequence[str]) -> bool:
    """Return whether any path or module segment names generated code."""

    return any(
        segment.lower() in {"generated", "autogenerated"}
        or segment.lower().startswith(("generated", "autogenerated"))
        for segment in segments
    )


def parse_imports(text: str) -> tuple[str, ...]:
    """Extract Lean module imports from supported text-level import forms."""

    return tuple(site.module for site in parse_import_sites(text))


def parse_import_sites(
    text: str,
    *,
    masked_text: str | None = None,
) -> tuple[LeanImport, ...]:
    """Extract Lean module imports with source line evidence."""

    cleaned = (
        mask_lean_comments_and_strings(text)
        if masked_text is None
        else masked_text
    )
    original_lines = text.splitlines()
    imports: list[LeanImport] = []
    for line_number, line in enumerate(cleaned.splitlines(), start=1):
        import_text = original_lines[line_number - 1].split("--", 1)[0].strip()
        imports.extend(
            LeanImport(module=module, line=line_number, text=import_text)
            for module in parse_import_line(line)
        )
    return tuple(imports)


def parse_lexical_markers(
    text: str,
    *,
    masked_text: str | None = None,
) -> tuple[LeanLexicalMarker, ...]:
    """Return lightweight source markers useful for review triage."""

    cleaned = (
        mask_lean_comments_and_strings(text)
        if masked_text is None
        else masked_text
    )
    original_lines = text.splitlines()
    markers: list[LeanLexicalMarker] = []
    for line_number, clean_line in enumerate(cleaned.splitlines(), start=1):
        original = original_lines[line_number - 1].strip()
        code = clean_line.split("--", 1)[0]
        markers.extend(trust_construct_markers(line_number, code, original))
        markers.extend(todo_markers(line_number, original))
    return tuple(markers)


def trust_construct_markers(
    line_number: int,
    code: str,
    original: str,
) -> list[LeanLexicalMarker]:
    """Return `sorry`/`admit`/`axiom` markers from code text only."""

    return [
        LeanLexicalMarker(kind=match.group(0), line=line_number, text=original)
        for match in TRUST_CONSTRUCT_RE.finditer(code)
    ]


def todo_markers(line_number: int, original: str) -> list[LeanLexicalMarker]:
    """Return TODO/FIXME markers from the original source line."""

    return [
        LeanLexicalMarker(kind=match.group(0).lower(), line=line_number, text=original)
        for match in TODO_RE.finditer(original)
    ]


def parse_import_line(line: str) -> tuple[str, ...]:
    """Parse one Lean import line after block comments have been masked."""

    tokens = import_tokens(line)
    if not starts_import_command(tokens):
        return ()
    return module_tokens(tokens[import_module_start(tokens):])


def import_tokens(line: str) -> list[str]:
    """Return whitespace tokens before a trailing Lean line comment."""

    return line.split("--", 1)[0].strip().split()


def starts_import_command(tokens: Sequence[str]) -> bool:
    """Return whether tokens begin with a supported Lean import form."""

    return import_keyword_index(tokens) is not None


def import_module_start(tokens: Sequence[str]) -> int:
    """Return the token index where imported module names start."""

    index = import_keyword_index(tokens)
    if index is None:
        return len(tokens)
    first_module = index + 1
    return first_module + int(first_module < len(tokens) and tokens[first_module] == "all")


def import_keyword_index(tokens: Sequence[str]) -> int | None:
    """Return the `import` token position after supported modifiers."""

    index = consume_prefix(tokens, 0, "public")
    index = consume_prefix(tokens, index, "meta")
    return index if index < len(tokens) and tokens[index] == "import" else None


def consume_prefix(tokens: Sequence[str], index: int, token: str) -> int:
    """Consume one optional token at `index`."""

    return index + 1 if index < len(tokens) and tokens[index] == token else index


def module_tokens(tokens: Sequence[str]) -> tuple[str, ...]:
    """Keep syntactically plausible module-name tokens."""

    return tuple(token for token in tokens if IMPORT_MODULE_RE.match(token))


def parse_text_declarations(
    text: str,
    *,
    masked_text: str | None = None,
) -> tuple[LeanTextDeclaration, ...]:
    """Return bounded declaration candidates from masked source text."""

    masked = (
        mask_lean_comments_and_strings(text)
        if masked_text is None
        else masked_text
    )
    return tuple(
        text_declaration(match, masked)
        for match in DECL_RE.finditer(masked)
    )


def text_declaration(
    match: re.Match[str],
    masked: str,
) -> LeanTextDeclaration:
    """Build one source-located lexical declaration candidate."""

    start = match.start("name")
    end = match.end("name")
    line = masked.count("\n", 0, start) + 1
    line_start = masked.rfind("\n", 0, start) + 1
    return LeanTextDeclaration(
        name=match.group("name"),
        kind=match.group("kind"),
        line=line,
        column=start - line_start + 1,
        start_offset=start,
        end_offset=end,
    )


def mask_lean_comments_and_strings(text: str) -> str:
    """Mask nested comments and strings while preserving offsets/newlines."""

    output: list[str] = []
    index = 0
    block_depth = 0
    line_comment = False
    in_string = False
    escaped = False
    while index < len(text):
        pair = text[index:index + 2]
        char = text[index]
        if char == "\n":
            output.append(char)
            line_comment = False
            index += 1
            continue
        if line_comment:
            output.append(" ")
            index += 1
            continue
        if block_depth:
            block_depth, index = mask_block_pair(
                pair,
                block_depth,
                index,
                output,
            )
            continue
        if in_string:
            in_string, escaped = mask_string_char(char, escaped)
            output.append(" ")
            index += 1
            continue
        if pair == "--":
            line_comment = True
            output.extend("  ")
            index += 2
            continue
        if pair == "/-":
            block_depth = 1
            output.extend("  ")
            index += 2
            continue
        if char == '"':
            in_string = True
            output.append(" ")
            index += 1
            continue
        output.append(char)
        index += 1
    return "".join(output)


def mask_block_pair(
    pair: str,
    depth: int,
    index: int,
    output: list[str],
) -> tuple[int, int]:
    """Mask one block-comment position and update nested depth."""

    if pair == "/-":
        output.extend("  ")
        return depth + 1, index + 2
    if pair == "-/":
        output.extend("  ")
        return depth - 1, index + 2
    output.append(" ")
    return depth, index + 1


def mask_string_char(char: str, escaped: bool) -> tuple[bool, bool]:
    """Update string state for one already-masked character."""

    if escaped:
        return True, False
    if char == "\\":
        return True, True
    if char == '"':
        return False, False
    return True, False


def mask_lean_block_comments(text: str) -> str:
    """Compatibility alias for the stronger offset-preserving masker."""

    return mask_lean_comments_and_strings(text)


def discover_modules(repo_root: Path, raw_root: str | None) -> ModuleDiscovery:
    """Discover the clean-core module inventory for one analysis root.

    Missing or ambiguous roots raise `ValueError`; callers decide how to render
    that failure for CLI users.
    """

    root = repo_root.resolve()
    layout = discover_lean_source_map(root)
    if layout.status == "lake_declared":
        return discover_declared_modules(root, raw_root, layout)
    return discover_conventional_modules(root, raw_root, layout)


def discover_conventional_modules(
    root: Path,
    raw_root: str | None,
    layout: LeanSourceMap,
) -> ModuleDiscovery:
    """Retain the documented repository-relative fallback behavior."""

    root_file = resolve_root_file(root, raw_root)
    root_module = module_name(root, root_file)
    inventory_root = inventory_root_for(root_file, root)
    modules = {
        module.name: module
        for module in (parse_lean_module(root, path) for path in inventory_files(root, inventory_root))
    }
    return ModuleDiscovery(
        repo_root=root,
        analysis_root_file=root_file,
        analysis_root_module=root_module,
        inventory_root=inventory_root,
        modules=dict(sorted(modules.items())),
        discovery_status=layout.status,
        diagnostics=layout.diagnostics,
        source_roots=tuple(str(item.path.relative_to(root)) for item in layout.roots),
    )


def discover_declared_modules(
    root: Path,
    raw_root: str | None,
    layout: LeanSourceMap,
) -> ModuleDiscovery:
    """Resolve roots and inventory through Lake-declared source directories."""

    root_file, root_module = resolve_declared_root(root, raw_root, layout)
    inventory_root = root_module.split(".", 1)[0]
    selected = {
        name: path
        for name, path in layout.modules.items()
        if name == inventory_root or name.startswith(f"{inventory_root}.")
    }
    if root_module not in selected and root_file.is_file():
        selected[root_module] = root_file
    modules = {
        name: parse_lean_module(root, path, resolved_name=name)
        for name, path in sorted(selected.items())
    }
    return ModuleDiscovery(
        repo_root=root,
        analysis_root_file=root_file,
        analysis_root_module=root_module,
        inventory_root=inventory_root,
        modules=modules,
        discovery_status=layout.status,
        diagnostics=layout.diagnostics,
        source_roots=tuple(str(item.path.relative_to(root)) for item in layout.roots),
    )


def resolve_declared_root(
    repo_root: Path,
    raw_root: str | None,
    layout: LeanSourceMap,
) -> tuple[Path, str]:
    """Resolve a module or declared-root-relative path without guessing."""

    if raw_root and raw_root in layout.modules:
        return layout.modules[raw_root], raw_root
    if raw_root:
        path = declared_root_path(repo_root, raw_root)
        if path is not None:
            return path, declared_module_name(path, layout)
        raise ValueError(
            f"could not resolve analysis root {raw_root!r} through Lake-declared "
            f"source roots: {', '.join(str(root.path) for root in layout.roots)}"
        )
    top_level = [
        (name, path)
        for name, path in layout.modules.items()
        if "." not in name
    ]
    if len(top_level) == 1:
        name, path = top_level[0]
        return path, name
    raise ValueError("Lake layout does not select one unambiguous root; pass --root")


def declared_root_path(repo_root: Path, raw_root: str) -> Path | None:
    """Return one existing caller path inside the target repository."""

    raw_path = Path(raw_root)
    path = raw_path if raw_path.is_absolute() else repo_root / raw_path
    if not path.exists():
        return None
    return ensure_inside_repo(repo_root, path.resolve())


def declared_module_name(path: Path, layout: LeanSourceMap) -> str:
    """Map one path through its most-specific declared source root."""

    source_root = root_for_path(path, layout.roots)
    if source_root is None:
        raise ValueError(
            f"analysis root {path} is outside every Lake-declared source root"
        )
    return module_name_under_root(source_root.path, path)
