"""Public facade for Ladon's typed report-v2 contract."""

from ladon.report_adapters import (
    build_report_v2,
    coerce_report_v2,
    mark_report_phase_required,
    replace_report_phase,
    report_version,
    supported_report_view,
    update_report_metadata,
)
from ladon.report_contract import (
    EXTENSION_NAMES,
    PHASE_DISPOSITIONS,
    PHASE_NAMES,
    PHASE_STATUSES,
    REPORT_VERSION,
    SECTION_PHASES,
    V1_REPORT_VERSION,
    Diagnostic,
    ExtensionEnvelope,
    Finding,
    PhaseEnvelope,
    Provenance,
    ReportMetadata,
    ReportModelError,
    UnsupportedReportVersionError,
)
from ladon.report_model import ReportV2
from ladon.report_serialization import (
    SerializationResult,
    SerializedReportBytes,
    canonical_json_bytes,
    load_report_schema,
    normalized_report_payload,
    serialize_report,
    serialize_report_bytes,
    serialize_v1_json,
)


__all__ = [
    "EXTENSION_NAMES",
    "PHASE_DISPOSITIONS",
    "PHASE_NAMES",
    "PHASE_STATUSES",
    "REPORT_VERSION",
    "SECTION_PHASES",
    "V1_REPORT_VERSION",
    "Diagnostic",
    "ExtensionEnvelope",
    "Finding",
    "PhaseEnvelope",
    "Provenance",
    "ReportMetadata",
    "ReportModelError",
    "ReportV2",
    "SerializationResult",
    "SerializedReportBytes",
    "UnsupportedReportVersionError",
    "build_report_v2",
    "canonical_json_bytes",
    "coerce_report_v2",
    "load_report_schema",
    "mark_report_phase_required",
    "normalized_report_payload",
    "replace_report_phase",
    "report_version",
    "serialize_report",
    "serialize_report_bytes",
    "serialize_v1_json",
    "supported_report_view",
    "update_report_metadata",
]
